name: Construct World of Padman for R36S

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04-arm64
    # Nutzt Ubuntu 20.04 um kompatible glibc-Abhängigkeiten für den R36S zu garantieren
    container:
      image: ubuntu:20.04

    steps:
      - name: Install Git & Sudo (Prerequisites)
        run: |
          apt-get update
          DEBIAN_FRONTEND=noninteractive apt-get install -y git sudo curl

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Cache ccache
        uses: actions/cache@v4
        with:
          path: ~/.ccache
          key: ${{ runner.os }}-ccache-ubuntu2004-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-ccache-ubuntu2004-

      - name: Make Build Script Executable
        run: chmod +x build.sh

      - name: Build World of Padman
        run: ./build.sh

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: worldofpadman-r36s-optimized
          path: artifact/
          if-no-files-found: error
